# Generated by Django 4.2.6 on 2023-10-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=32)),
                ("account", models.CharField(blank=True, max_length=32)),
                ("email", models.CharField(blank=True, max_length=32)),
                ("phone_number", models.CharField(blank=True, max_length=32)),
                ("group", models.CharField(blank=True, max_length=32)),
            ],
        ),
    ]
